question_data = [{"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "In 2016, the United Kingdom voted to stay in the EU.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Bill Cipher in the show &quot;Gravity Falls&quot; is the good guy.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039; history.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Minecraft can be played with a virtual reality headset.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the nickname Kyon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "easy",
                  "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Art", "type": "boolean", "difficulty": "easy",
                  "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Activision created Battlefield 1.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                  "question": "A scalene triangle has two sides of equal length.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
